### ISSUE TITLE
Ready for use?

### ISSUE THREAD

**Issue by TedDriggs** [stbuehler/rust-xml-data#2]
This crate exactly solves a problem I've run into, and I'd like to use it, but the 0.0.1 version number makes me worry it's experimental and/or abandoned. Is this maintained/are there any known issues?

**Comment by stbuehler** [comment]
I don't known of any issues, and it should be safe to use if it supports what you need.

Otoh the design completely ignores XML namespaces; i.e. it only supports a very limited subset of XML (I have another unpublished project where I'm trying to design traits for handling XML namespaces properly).
